//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hire
    {
        public int Hire_Id { get; set; }
        public Nullable<System.DateTime> Hire_Date { get; set; }
        public string Hire_Remarks { get; set; }
        public int Cust_Id { get; set; }
        public int prof_Id { get; set; }
        public Nullable<int> Prof_Cat_Id { get; set; }
        public Nullable<bool> IsHired { get; set; }
    
        public virtual Professional Professional { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Professional Professional1 { get; set; }
    }
}
