//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professional()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Hires = new HashSet<Hire>();
        }
    
        public int prof_Id { get; set; }
        public string Prof_FirstName { get; set; }
        public string Prof_LastName { get; set; }
        public string Prof_EmailID { get; set; }
        public Nullable<System.DateTime> Prof_DateOfBirth { get; set; }
        public string Prof_Password { get; set; }
        public bool Prof_IsEmailVerified { get; set; }
        public Nullable<System.Guid> Prof_ActivationCode { get; set; }
        public string Prof_ResetPasswordCode { get; set; }
        public string Prof_Address { get; set; }
        public string Prof_CNIC { get; set; }
        public string Prof_PhoneNumber { get; set; }
        public bool Prof_IsBanned { get; set; }
        public string Prof_img { get; set; }
        public string Prof_Gender { get; set; }
        public string Prof_City { get; set; }
        public string Prof_Province_State { get; set; }
        public Nullable<int> Prof_Cat_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hire> Hires { get; set; }
        public virtual Hire Hire { get; set; }
        public virtual ProfessionalCategory ProfessionalCategory { get; set; }
    }
}
